package bsi.quiz.io;

import java.io.FileReader;
import java.io.IOException;

import javax.swing.ButtonModel;
import javax.swing.JRadioButton;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author ADIMAS-DEV
 */
public class views extends javax.swing.JFrame {
    private StringBuilder jsonContent = new StringBuilder();
    private String[] selectedAnswers = new String[10];
    private int halaman = 0;
    private int benar = 0;
    private int salah = 0;

    /**
     * Creates new form NewJFrame
     */
    public views() {
        initComponents();
    }

    public void setPelajaran(String mapel, String namanya) {
        pelajaran.setText(mapel);
        names.setText(namanya);
    }

    public void pindahHalaman(String halaman) {
        java.awt.CardLayout card = (java.awt.CardLayout) getContentPane().getLayout();
        card.show(getContentPane(), halaman);
    }
    
    public void setSoal() {
        try (FileReader reader = new FileReader("./src/main/java/bsi/quiz/io/data.json")) {
            if (halaman == 0) {
                jsonContent.setLength(0); // Clear the StringBuilder
            }

            if (jsonContent.length() == 0) {
                int i;
                while ((i = reader.read()) != -1) {
                    jsonContent.append((char) i); 
                }
            }

            JSONArray jsonArray = new JSONArray(jsonContent.toString());
            JSONObject firstQuestion = jsonArray.getJSONObject(halaman);

            String pertanyaan = firstQuestion.getString("pertanyaan");
            JSONArray pilihan = firstQuestion.getJSONArray("pilihan");

            soal.setText("<html>" + pertanyaan + "</html>");

            // Set the text and action command for each radio button
            for (int j = 0; j < pilihan.length(); j++) {
                JRadioButton radioButton = null;
                switch (j) {
                    case 0: radioButton = pilihan_1; break;
                    case 1: radioButton = pilihan_2; break;
                    case 2: radioButton = pilihan_3; break;
                    case 3: radioButton = pilihan_4; break;
                    case 4: radioButton = pilihan_5; break;
                }
                if (radioButton != null) {
                    radioButton.setText(pilihan.getString(j));
                    radioButton.setActionCommand(pilihan.getString(j)); // Set action command
                }
            }

            buttonGroup1.clearSelection();

            if (selectedAnswers[halaman] != null) {
                // Find the selected radio button by its text
                for (int j = 0; j < pilihan.length(); j++) {
                    JRadioButton radioButton = null;
                    switch (j) {
                        case 0: radioButton = pilihan_1; break;
                        case 1: radioButton = pilihan_2; break;
                        case 2: radioButton = pilihan_3; break;
                        case 3: radioButton = pilihan_4; break;
                        case 4: radioButton = pilihan_5; break;
                    }
                    if (radioButton != null && selectedAnswers[halaman].equals(radioButton.getText())) {
                        radioButton.setSelected(true);
                        break; // Stop searching once found
                    }
                }
            }
        } catch (IOException | JSONException e) {
            e.printStackTrace();
        }
    }


    //private void checkAnswer

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        home = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mata_pelajaran = new javax.swing.JComboBox<>();
        btn_mulai = new javax.swing.JButton();
        quiz = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pelajaran = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        names = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        soal = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        pilihan_1 = new javax.swing.JRadioButton();
        pilihan_2 = new javax.swing.JRadioButton();
        pilihan_3 = new javax.swing.JRadioButton();
        pilihan_4 = new javax.swing.JRadioButton();
        pilihan_5 = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        soal_sebelumnya = new javax.swing.JButton();
        soal_selanjutnya = new javax.swing.JButton();
        result = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jawaban_benar = new javax.swing.JLabel();
        jawaban_salah = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        main_lagi = new javax.swing.JButton();
        keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quiz.Io");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NAMA KAMU");

        nama.setBackground(new java.awt.Color(102, 153, 255));
        nama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setPreferredSize(new java.awt.Dimension(70, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MATA PELAJARAN");

        mata_pelajaran.setBackground(new java.awt.Color(102, 153, 255));
        mata_pelajaran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mata_pelajaran.setForeground(new java.awt.Color(255, 255, 255));
        mata_pelajaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BAHASA INDONESIA", "PKN", "AGAMA" }));
        mata_pelajaran.setMinimumSize(new java.awt.Dimension(72, 30));
        mata_pelajaran.setPreferredSize(new java.awt.Dimension(72, 30));

        btn_mulai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_mulai.setText("MULAI");
        btn_mulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mulaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mata_pelajaran, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_mulai, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mata_pelajaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_mulai, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(home, "card4");

        quiz.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));

        pelajaran.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pelajaran.setForeground(new java.awt.Color(255, 255, 255));
        pelajaran.setText("[ MAPEL ]");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quiz.Io");

        names.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        names.setForeground(new java.awt.Color(255, 255, 255));
        names.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        names.setText("[ Nama ]");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pelajaran, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(115, 115, 115)
                .addComponent(names, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(names, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pelajaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(102, 153, 255));

        soal.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        soal.setForeground(new java.awt.Color(255, 255, 255));
        soal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        soal.setToolTipText("");
        soal.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(soal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(soal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(102, 153, 255));

        pilihan_1.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroup1.add(pilihan_1);
        pilihan_1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pilihan_1.setForeground(new java.awt.Color(255, 255, 255));
        pilihan_1.setText("[ PILIHAN 1 ]");

        pilihan_2.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroup1.add(pilihan_2);
        pilihan_2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pilihan_2.setForeground(new java.awt.Color(255, 255, 255));
        pilihan_2.setText("[ PILIHAN 2 ]");

        pilihan_3.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroup1.add(pilihan_3);
        pilihan_3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pilihan_3.setForeground(new java.awt.Color(255, 255, 255));
        pilihan_3.setText("[ PILIHAN 3 ]");

        pilihan_4.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroup1.add(pilihan_4);
        pilihan_4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pilihan_4.setForeground(new java.awt.Color(255, 255, 255));
        pilihan_4.setText("[ PILIHAN 4 ]");

        pilihan_5.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroup1.add(pilihan_5);
        pilihan_5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pilihan_5.setForeground(new java.awt.Color(255, 255, 255));
        pilihan_5.setText("[ PILIHAN 5 ]");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pilihan_1)
                    .addComponent(pilihan_2)
                    .addComponent(pilihan_3)
                    .addComponent(pilihan_4)
                    .addComponent(pilihan_5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pilihan_1)
                .addGap(15, 15, 15)
                .addComponent(pilihan_2)
                .addGap(15, 15, 15)
                .addComponent(pilihan_3)
                .addGap(15, 15, 15)
                .addComponent(pilihan_4)
                .addGap(15, 15, 15)
                .addComponent(pilihan_5)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(102, 153, 255));

        soal_sebelumnya.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        soal_sebelumnya.setText("SEBELUMNYA");
        soal_sebelumnya.setPreferredSize(new java.awt.Dimension(70, 23));
        soal_sebelumnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soal_sebelumnyaActionPerformed(evt);
            }
        });

        soal_selanjutnya.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        soal_selanjutnya.setText("LANJUT");
        soal_selanjutnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soal_selanjutnyaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(soal_sebelumnya, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(soal_selanjutnya, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soal_sebelumnya, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(soal_selanjutnya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout quizLayout = new javax.swing.GroupLayout(quiz);
        quiz.setLayout(quizLayout);
        quizLayout.setHorizontalGroup(
            quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        quizLayout.setVerticalGroup(
            quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(quiz, "card3");

        result.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(102, 153, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Quiz.Io");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(102, 153, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Jawaban Benar");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Jawaban Salah");

        jawaban_benar.setFont(new java.awt.Font("Segoe UI Black", 1, 60)); // NOI18N
        jawaban_benar.setForeground(new java.awt.Color(153, 255, 153));
        jawaban_benar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jawaban_benar.setText("8");

        jawaban_salah.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jawaban_salah.setForeground(new java.awt.Color(255, 51, 51));
        jawaban_salah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jawaban_salah.setText("2");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jawaban_benar, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jawaban_salah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jawaban_benar, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(jawaban_salah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(102, 153, 255));

        main_lagi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        main_lagi.setText("MAIN LAGI");
        main_lagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_lagiActionPerformed(evt);
            }
        });

        keluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main_lagi, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(main_lagi, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout resultLayout = new javax.swing.GroupLayout(result);
        result.setLayout(resultLayout);
        resultLayout.setHorizontalGroup(
            resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        resultLayout.setVerticalGroup(
            resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(result, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mulaiActionPerformed
        // TODO add your handling code here:
        selectedAnswers = new String[10];
        setPelajaran(mata_pelajaran.getSelectedItem().toString(), nama.getText());
        pindahHalaman("card3");
        setSoal();
    }//GEN-LAST:event_btn_mulaiActionPerformed

    private void soal_sebelumnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soal_sebelumnyaActionPerformed
        // TODO add your handling code here:
        ButtonModel selectedButton = buttonGroup1.getSelection();

        if (selectedButton == null) {
            System.out.println("Pilih salah satu jawaban.");
            return; // Hentikan eksekusi jika tidak ada pilihan
        }

       // Ambil teks dari radio button yang dipilih menggunakan getActionCommand()
        String selectedAnswer = selectedButton.getActionCommand(); 
        selectedAnswers[halaman] = selectedAnswer;

        // Check if it's the last question
        if (halaman == 0) { 
            pindahHalaman("card4");
        } else {
            halaman--;
        }
        setSoal();
    }//GEN-LAST:event_soal_sebelumnyaActionPerformed

    private void checkAnswers() {
        try {
            JSONArray jsonArray = new JSONArray(jsonContent.toString()); 

            benar = 0;
            salah = 0;

            for (int j = 0; j < jsonArray.length(); j++) {
                JSONObject question = jsonArray.getJSONObject(j);
                String correctAnswer = question.getString("jawaban");
                String selectedAnswer = selectedAnswers[j];

                if (selectedAnswer != null && selectedAnswer.equals(correctAnswer)) {
                    benar++;
                } else {
                    salah++;
                }
            }

            // Update UI
            jawaban_benar.setText(String.valueOf(benar));
            jawaban_salah.setText(String.valueOf(salah));

        } catch (JSONException e) { 
            e.printStackTrace();
        }
    }

    private void soal_selanjutnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soal_selanjutnyaActionPerformed
        // TODO add your handling code here:
        ButtonModel selectedButton = buttonGroup1.getSelection();

        if (selectedButton == null) {
            System.out.println("Pilih salah satu jawaban.");
            return; // Hentikan eksekusi jika tidak ada pilihan
        }

        // Ambil teks dari radio button yang dipilih menggunakan getActionCommand()
        String selectedAnswer = selectedButton.getActionCommand(); 
        selectedAnswers[halaman] = selectedAnswer; // Simpan jawaban yang dipilih

        // Check if it's the last question
        if (halaman == 9) {
            checkAnswers(); // Check all answers before moving to results
            pindahHalaman("card2");
        } else {
            halaman++;
        }
        setSoal();
    }//GEN-LAST:event_soal_selanjutnyaActionPerformed

    private void main_lagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_lagiActionPerformed
        // TODO add your handling code here:
        pindahHalaman("card4");
        nama.setText("");
    }//GEN-LAST:event_main_lagiActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mulai;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jawaban_benar;
    private javax.swing.JLabel jawaban_salah;
    private javax.swing.JButton keluar;
    private javax.swing.JButton main_lagi;
    private javax.swing.JComboBox<String> mata_pelajaran;
    private javax.swing.JTextField nama;
    private javax.swing.JLabel names;
    private javax.swing.JLabel pelajaran;
    private javax.swing.JRadioButton pilihan_1;
    private javax.swing.JRadioButton pilihan_2;
    private javax.swing.JRadioButton pilihan_3;
    private javax.swing.JRadioButton pilihan_4;
    private javax.swing.JRadioButton pilihan_5;
    private javax.swing.JPanel quiz;
    private javax.swing.JPanel result;
    private javax.swing.JLabel soal;
    private javax.swing.JButton soal_sebelumnya;
    private javax.swing.JButton soal_selanjutnya;
    // End of variables declaration//GEN-END:variables
}
